Estoque.PRT/Estoque.PRT/Models/Entities/Change.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using System.Web;
using Taugor.PRT.Models;
using Taugor.PRT.Models.Enums;

namespace Taugor.PRT.Models
{
    //[Table("Changes")]
    public partial class Change : ICanHazAttachments
    {
        [DisplayName("Código")]
        [Key]
        public int ChangeId { get; set; }

        [DisplayName("Descrição de Desenvolvimento")]
        [DataType(DataType.MultilineText)]
        public string DevelopmentDescription { get; set; }

        [DisplayName("Descrição Interna")]
        [DataType(DataType.MultilineText)]
        public string InternalDescription { get; set; }

        [DisplayName("Descrição")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DisplayName("Versão")]
        public int VersionId { get; set; }
        
        [ForeignKey("VersionId")]
        [DisplayName("Versão")]
        public virtual Version Version { get; set; }

        [DisplayName("Tipo")]
        [EnumDataType(typeof(ChangeType))]
        public ChangeType Type { get; set; }

        [DisplayName("Escopo")]
        [EnumDataType(typeof(Visibility))]
        
        public Visibility Visibility { get; set; }

        [DisplayName("Data")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Date { get; set; }

        [NotMapped]
        [DisplayName("Código")]
        public string Identifier { get { return string.Format("CH{0:000000000}", ChangeId); } }


    }
}

Estoque.PRT/Estoque.PRT/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Taugor.PRT.Models.DBContext;
using Taugor.PRT.Models;

namespace Taugor.PRT.Controllers
{
    public class ProductController : Controller
    {
        private TaugorPRTContext db = new TaugorPRTContext();

        // GET: /Product/
        public async Task<ActionResult> Index(int? id = null)
        {
            await db.Products.LoadAsync();
            ViewBag.Context = db;
            if (id.HasValue)
            {
                return View(await db.Products
                    .Where(k => k.ProductId == id && k.ParentId != id)
                    .ToListAsync());

            }
            else
            {
                return View(await db.Products
                    .Where(k => k.ParentId == null)
                    .ToListAsync());
            }

        }

        public async Task<ActionResult> Modules(int id)
        {
            await db.Products.LoadAsync();
            ViewBag.Context = db;

            return View(await db.Products
                .Where(k => k.ProductId == id || k.ParentId == id)
                .ToListAsync());


        }

        // GET: /Product/Roadmap/5
        public async Task<ActionResult> Roadmap(int? id)
        {
            ViewBag.Context = db;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }



        // GET: /Product/Create
        [Authorize]
        public ActionResult Create(int? BaseId = null)
        {
            var product = db.Products.Find(BaseId);

            if (BaseId.HasValue)
            {
                ViewBag.ParentId = new SelectList(db.Products, "ProductId", "Name", BaseId);
            }
            else
            {
                ViewBag.ParentId = new SelectList(db.Products, "ProductId", "Name");
            }

            if (product != null)
            {
                return View(new Product() { ParentId = BaseId, Name = product.Name + " - " });
            }
            else
            {
                return View();
            }

        }

        // POST: /Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create([Bind(Include = "ProductId,Name,ShortDescription,Description,ParentId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ParentId = new SelectList(db.Products, "ProductId", "Name", product.ParentId);
            return View(product);
        }

        // GET: /Product/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.ParentId = new SelectList(db.Products, "ProductId", "Name", product.ParentId);

            return View(product);
        }

        // POST: /Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit([Bind(Include = "ProductId,Name,ShortDescription,Description,ParentId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ParentId = new SelectList(db.Versions, "ProductId", "Name", product.ParentId);
            return View(product);
        }

        // GET: /Product/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            ViewBag.Context = db;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: /Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Product product = await db.Products.FindAsync(id);
            db.Products.Remove(product);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Estoque.PRT/Estoque.PRT/Controllers/VersionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Taugor.PRT.Models;
using Prt = Taugor.PRT.Models;
using Taugor.PRT.Models.DBContext;

namespace Taugor.PRT.Controllers
{
    public class VersionController : Controller
    {
        private TaugorPRTContext db = new TaugorPRTContext();

        // GET: /Version/
        public async Task<ActionResult> Index()
        {
            var versions = db.Versions.Include(v => v.Product);
            return View(await versions.ToListAsync());
        }


        // GET : /Version/Product/5
        public ActionResult Product(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var modules = db.Products.Where(k => k.ProductId == id || k.ParentId == id)
                .Include(v => v.Versions);
            var versions = new List<Prt.Version>();

            modules.ToList().ForEach(k => versions.AddRange(k.Versions.Where(v => !v.IsRoadmap)));

            if (versions == null || versions.Count() == 0)
            {
                return HttpNotFound();
            }
            db.Products.Load();
            db.Changes.Load();

            return View(versions
                .OrderByDescending(k => k.ReleaseDate)
                .ThenByDescending(k => k.ReleasePlan)
                );
        }

        public ActionResult Module(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var versions = db.Versions.Where(k => k.ProductId == id)
                .Include(v => v.Product).ToList().Where(k => !k.IsRoadmap);
                //.Include(v => v.Changes)
                ;
            if (versions == null || versions.Count() == 0)
            {
                return HttpNotFound();
            }
            db.Products.Load();
            db.Changes.Load();

            return View(versions);
        }


        // GET: /Version/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var partial = id < 0;
            if (partial) { id *= -1; }
            Prt.Version version = await db.Versions.FindAsync(id);
            if (version == null)
            {
                return HttpNotFound();
            }
            db.Products.Load();
            db.Changes.Load();
            //ViewBag.Changes = version.Changes.Cast<Changelogs.Models.Change>();
            ViewBag.Partial = partial;
            return partial ? (ActionResult) PartialView(version) : View(version);
        }

        // GET: /Version/Create
        [Authorize]
        public ActionResult Create(int? ProductId = null)
        {
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "Name");
            if (ProductId.HasValue)
            {
                return View(new Prt.Version() { ProductId = ProductId.Value });
            }
            else
            {
                return View();
            }
            
        }

        // POST: /Version/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create([Bind(Include = "VersionId,Type,FullVersion,ProductId,MajorVersion,MinorVersion,Build,Revision,Codename,TypeId,ReleaseDate,ReleasePlan,Author")] Prt.Version version)
        {
            if (ModelState.IsValid)
            {
                db.Versions.Add(version);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { Id = version.VersionId });
            }

            ViewBag.ProductId = new SelectList(db.Products.Where(k => k.ParentId == null), "ProductId", "Name", version.ProductId);
            return View(version);
        }

        // GET: /Version/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prt.Version version = await db.Versions.FindAsync(id);
            if (version == null)
            {
                return HttpNotFound();
            }

            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "Name", version.ProductId);
            return View(version);
        }

        // POST: /Version/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit([Bind(Include = "VersionId,Type,FullVersion,ProductId,MajorVersion,MinorVersion,Build,Revision,Codename,TypeId,ReleaseDate,ReleasePlan,Author")] Prt.Version version)
        {
            if (ModelState.IsValid)
            {
                db.Entry(version).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { Id = version.VersionId });
            }
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "Name", version.ProductId);
            return View(version);
        }

        // GET: /Version/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Prt.Version version = await db.Versions.FindAsync(id);
            db.Versions.Load();
            db.Changes.Load();
            //ViewBag.Changes = version.Changes.Cast<Changelogs.Models.Change>();
            if (version == null)
            {
                return HttpNotFound();
            }
            return View(version);
        }

        // POST: /Version/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Prt.Version version = await db.Versions.FindAsync(id);
            db.Versions.Load();
            db.Changes.Load();
            //ViewBag.Changes = version.Changes.Cast<Changelogs.Models.Change>();
            db.Versions.Remove(version);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Estoque.PRT/Estoque.PRT/Views/Change/Create.cshtml
@model Taugor.PRT.Models.Change
@using Taugor.PRT.Models
@using Taugor.PRT.Models.ViewModels
@using Taugor.PRT.Models.Enums
@using Taugor.PRT.Util

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Change</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.VersionId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VersionId", String.Empty)
                @Html.ValidationMessageFor(model => model.VersionId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Visibility, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Visibility, MVCSelectHelper.GetSelectList<Visibility>())
                @Html.ValidationMessageFor(model => model.Visibility)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, MVCSelectHelper.GetSelectList<ChangeType>())
                @Html.ValidationMessageFor(model => model.Type)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InternalDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InternalDescription)
                @Html.ValidationMessageFor(model => model.InternalDescription)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DevelopmentDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DevelopmentDescription)
                @Html.ValidationMessageFor(model => model.DevelopmentDescription)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date)
                @Html.ValidationMessageFor(model => model.Date)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-default" })
</div>

Estoque.PRT/Estoque.PRT/Views/Change/Delete.cshtml
@model Taugor.PRT.Models.Change
@using Taugor.PRT.Models
@using Taugor.PRT.Models.ViewModels
@using Taugor.PRT.Models.Enums
@using Taugor.PRT.Util
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Change</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Version.FullVersion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Version.FullVersion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Visibility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Visibility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Voltar", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-default" })
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

Estoque.PRT/Estoque.PRT/Views/Change/Details.cshtml
@model Taugor.PRT.Models.Change
@using Taugor.PRT.Models
@using Taugor.PRT.Models.ViewModels
@using Taugor.PRT.Models.Enums
@using Taugor.PRT.Util
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Change</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Version.ProductId)
        </dt>
        <dd>
            <span data-toggle="tooltip" title="Detalhes do Produto">
                @Html.ActionLink(@Html.DisplayFor(model => model.Version.Product.Name).ToString(), "Details", "Product", new { id = Model.Version.ProductId }, null)
            </span>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Version.FullVersion)
        </dt>

        <dd>
            <span data-toggle="tooltip" title="Detalhes da Versão">
                @Html.ActionLink(@Html.DisplayFor(model => model.Version.FullVersion).ToString(), "Details", "Version", new { id = Model.VersionId }, null)
            </span>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Visibility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Visibility)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>



    </dl>
</div>
<p>

    @if (Request.IsAuthenticated)
    {
        @Html.ActionLink("Editar", "Edit", new { id = Model.ChangeId }) <span>|</span>
    }
    @Html.ActionLink("Voltar", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-default" })
</p>

Estoque.PRT/Estoque.PRT/Views/Change/Edit.cshtml
@model Taugor.PRT.Models.Change
@using Taugor.PRT.Models
@using Taugor.PRT.Models.ViewModels
@using Taugor.PRT.Models.Enums
@using Taugor.PRT.Util

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Change</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ChangeId)

        <div class="form-group">
            @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, MVCSelectHelper.GetSelectList<ChangeType>())
                @Html.ValidationMessageFor(model => model.Type)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VersionId, "VersionId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VersionId", String.Empty)
                @Html.ValidationMessageFor(model => model.VersionId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Visibility, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Visibility, MVCSelectHelper.GetSelectList<Visibility>())
                @Html.ValidationMessageFor(model => model.Visibility)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, MVCSelectHelper.GetSelectList<ChangeType>())
                @Html.ValidationMessageFor(model => model.Type)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InternalDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InternalDescription)
                @Html.ValidationMessageFor(model => model.InternalDescription)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date)
                @Html.ValidationMessageFor(model => model.Date)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-default" })
</div>

Estoque.PRT/Estoque.PRT/Views/Change/Index.cshtml
@model IEnumerable<Taugor.PRT.Models.Change>
@using Taugor.PRT.Models
@using Taugor.PRT.Models.ViewModels
@using Taugor.PRT.Models.Enums
@using Taugor.PRT.Util
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@if (Request.IsAuthenticated)
{
    <p>
        @Html.ActionLink("Nova Alteração", "Create", new { }, new { @class = "btn btn-primary" })
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Version.Product)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Version.FullVersion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Visibility)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Version.Product.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Version.FullVersion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Visibility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.ActionLink("Ver Detalhes", "Details", new { id = item.ChangeId }, new { @class = "btn btn-info" })
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Editar", "Edit", new { id = item.ChangeId }, new { @class = "btn btn-warning" })
                }
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Excluir", "Delete", new { id = item.ChangeId }, new { @class = "btn btn-danger" })
                }
            </td>
        </tr>
    }

</table>