Estoque.PRT/Estoque.PRT/Controllers/ChangeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Taugor.PRT.Models;
using Taugor.PRT.Models.DBContext;

namespace Taugor.PRT.Controllers
{
    public class ChangeController : Controller
    {
        private TaugorPRTContext db = new TaugorPRTContext();

        // GET: /Change/
        public async Task<ActionResult> Index()
        {
            var changes = db.Changes.Include(c => c.Version).Include(c => c.Version.Product);
            return View(await changes.ToListAsync());
        }

        // GET: /Change/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            db.Products.Load();
            db.Versions.Load();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Change change = await db.Changes.FindAsync(id);
            if (change == null)
            {
                return HttpNotFound();
            }
            return View(change);
        }

        // GET: /Change/Create
        [Authorize]
        public ActionResult Create(int? VersionId = null)
        {
            db.Products.Load();
            db.Versions.Load();
            ViewBag.VersionId = new SelectList(db.Versions, "VersionId", "Reference", VersionId);
            if (VersionId.HasValue)
            {
                return View(new Change() { VersionId = VersionId.Value });
            }
            else
            {
                return View();
            }
            
        }

        // POST: /Change/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create([Bind(Include = "ChangeId,Type,VersionId,VisibilityId,TypeId,Description,Date")] Change change)
        {
            if (ModelState.IsValid)
            {
                db.Changes.Add(change);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Version", new { Id = change.VersionId });
            }

            ViewBag.VersionId = new SelectList(db.Versions, "VersionId", "FullVersion", change.VersionId);
            return View(change);
        }

        // GET: /Change/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            db.Products.Load();
            db.Versions.Load();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Change change = await db.Changes.FindAsync(id);
            if (change == null)
            {
                return HttpNotFound();
            }
            ViewBag.VersionId = new SelectList(db.Versions, "VersionId", "FullVersion", change.VersionId);
            return View(change);
        }

        // POST: /Change/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit([Bind(Include = "ChangeId,Type,VersionId,VisibilityId,TypeId,Description,Date")] Change change)
        {
            if (ModelState.IsValid)
            {
                db.Entry(change).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Version", new { Id = change.VersionId });
            }
            ViewBag.VersionId = new SelectList(db.Versions, "VersionId", "FullVersion", change.VersionId);
            return View(change);
        }

        // GET: /Change/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            db.Products.Load();
            db.Versions.Load();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Change change = await db.Changes.FindAsync(id);
            if (change == null)
            {
                return HttpNotFound();
            }
            return View(change);
        }

        // POST: /Change/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Change change = await db.Changes.FindAsync(id);
            db.Changes.Remove(change);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Estoque.PRT/Estoque.PRT/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Taugor.PRT.Models.DBContext;
using Taugor.PRT.Models;

namespace Taugor.PRT.Controllers
{
    public class ProductController : Controller
    {
        private TaugorPRTContext db = new TaugorPRTContext();

        // GET: /Product/
        public async Task<ActionResult> Index(int? id = null)
        {
            await db.Products.LoadAsync();
            ViewBag.Context = db;
            if (id.HasValue)
            {
                return View(await db.Products
                    .Where(k => k.ProductId == id && k.ParentId != id)
                    .ToListAsync());

            }
            else
            {
                return View(await db.Products
                    .Where(k => k.ParentId == null)
                    .ToListAsync());
            }

        }

        public async Task<ActionResult> Modules(int id)
        {
            await db.Products.LoadAsync();
            ViewBag.Context = db;

            return View(await db.Products
                .Where(k => k.ProductId == id || k.ParentId == id)
                .ToListAsync());


        }

        // GET: /Product/Roadmap/5
        public async Task<ActionResult> Roadmap(int? id)
        {
            ViewBag.Context = db;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }



        // GET: /Product/Create
        [Authorize]
        public ActionResult Create(int? BaseId = null)
        {
            var product = db.Products.Find(BaseId);

            if (BaseId.HasValue)
            {
                ViewBag.ParentId = new SelectList(db.Products, "ProductId", "Name", BaseId);
            }
            else
            {
                ViewBag.ParentId = new SelectList(db.Products, "ProductId", "Name");
            }

            if (product != null)
            {
                return View(new Product() { ParentId = BaseId, Name = product.Name + " - " });
            }
            else
            {
                return View();
            }

        }

        // POST: /Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create([Bind(Include = "ProductId,Name,ShortDescription,Description,ParentId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ParentId = new SelectList(db.Products, "ProductId", "Name", product.ParentId);
            return View(product);
        }

        // GET: /Product/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.ParentId = new SelectList(db.Products, "ProductId", "Name", product.ParentId);

            return View(product);
        }

        // POST: /Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit([Bind(Include = "ProductId,Name,ShortDescription,Description,ParentId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ParentId = new SelectList(db.Versions, "ProductId", "Name", product.ParentId);
            return View(product);
        }

        // GET: /Product/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            ViewBag.Context = db;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: /Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Product product = await db.Products.FindAsync(id);
            db.Products.Remove(product);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Estoque.PRT/Estoque.PRT/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Linq.Expressions;
using Taugor.PRT.Models;
using Taugor.PRT.Models.DBContext;
using Taugor.PRT.Models.ViewModels;
using Taugor.PRT.Models.Enums;

namespace Taugor.PRT.Controllers
{
    public class UserController : Controller
    {
        private TaugorPRTContext db = new TaugorPRTContext();

        
        public static IEnumerable<User> GetAllUsers()
        {
            TaugorPRTContext db = new TaugorPRTContext();
            return db.Users.ToList();
        }

        
        public static IEnumerable<User> GetAllUsers(Expression<Func<User, bool>> predicate)
        {
            TaugorPRTContext db = new TaugorPRTContext();
            return db.Users.Where(predicate).ToList();
        }

        
        public static IEnumerable<User> GetSupportUsers()
        {
            return GetAllUsers(k => k.Type <= UserType.Support);
        }
        // GET: /User/

        public async Task<ActionResult> Index()
        {
            return View(await db.Users.ToListAsync());
        }

        // GET: /User/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = await db.Users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: /User/Create
        public ActionResult Create()
        {
            ViewBag.Companies = db.Companies.ToList();
            return View();
        }

        // POST: /User/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: /User/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = await db.Users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.Companies = db.Companies.ToList();
            return View(new UserEditAdminVM(user));
        }

        // POST: /User/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(UserEditAdminVM userVM)
        {
            var user = await db.Users.FindAsync(userVM.UserId);
            if (ModelState.IsValid)
            {
                
                userVM.MapTo(user);
                db.Entry(user).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return Redirect(user.RedirectTo);
        }

        // GET: /User/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = await db.Users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: /User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            User user = await db.Users.FindAsync(id);
            db.Users.Remove(user);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Estoque.PRT/Estoque.PRT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Portal Relacionamento Taugor</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Taugor Changelogs", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            @Html.Partial("_Navbar")
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Taugor Corporation</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/forms")
    @Scripts.Render("~/bundles/bootstrap")
    @*@Scripts.Render("~/bundles/svg")*@
    @RenderSection("scripts", required: false)
    @*<script>
        $(document).ready(function () {
            setTimeout(function () { $('[data-toggle="tooltip"]').tooltip(); }, 1000);
        });
    </script>*@
</body>
</html>

Estoque.PRT/Estoque.PRT/Views/Shared/_MinimalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Changelogs</title>
    @Styles.Render("~/Content/bootstrap.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Changelogs", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Taugor Corporation</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Estoque.PRT/Estoque.PRT/Views/Shared/_Navbar.cshtml
@using Taugor.PRT.Models
@using Taugor.PRT.Models.Enums
@using Taugor.PRT.Models.DBContext
@{
    var db = new TaugorPRTContext();
    var user = db.Users.Where(k => k.Username == User.Identity.Name).FirstOrDefault();
}
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        @if (Request.IsAuthenticated && user != null)
        {
            if (user.Type <= UserType.Internal)
            {
                <li>@Html.ActionLink("Produtos", "Index", "Product")</li>
                <li>@Html.ActionLink("Versões", "Index", "Version")</li>
                <li>@Html.ActionLink("Mudanças", "Index", "Change")</li>
            }
            if (user.Type <= UserType.Support)
            {
                <li>@Html.ActionLink("Usuários", "Index", "User")</li>
            }
            <li>@Html.ActionLink("Chamados", "Index", "Request")</li>

            if (user.Type >= UserType.Partner)
            {
                <li>@Html.ActionLink("Sobre a Taugor", "About", "Home")</li>
                <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
            }
        }
        else
        {
            <li>@Html.ActionLink("Sobre a Taugor", "About", "Home")</li>
            <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
        }
    </ul>
    <ul class="nav navbar-nav navbar-right">
        @if (Request.IsAuthenticated && user != null)
        {
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> @User.Identity.Name</a></li>
            <li><a href="@Url.Action("Logoff", "Account")"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        }
        else
        {
            <li><a href="@Url.Action("Login", "Account")"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        }
    </ul>
</div>